const types = {
  APPLY_YEAR_FILTER: "APPLY_YEAR_FILTER",
  APPLY_DATE_FILTER: "APPLY_DATE_FILTER",
  PUSH_YEAR_FOR_MIS: "PUSH_YEAR_FOR_MIS",
  SET_LOADING: "SET_LOADING",
  ADD_DATE_FOR_FILTER: "ADD_DATE_FOR_FILTER",
};

export default types;
